<?php

$profile_id = $_GET['profileid'];

if (file_exists('../includes/connection.php')){
	require('../includes/connection.php');
}else{
	require("connection.php");
}

$sql = 'SELECT title FROM pages, fan_profile WHERE pages.filename = fan_profile.filename
AND profileid = '.$profile_id;
$query = mysql_query($sql);
$titlequery = mysql_fetch_assoc($query);
$title = $titlequery["title"];


include("../includes/header.php");
?>
</head>

<body>

<div id="menu">
<!--It used that the menu was made up of over 60 lines of code.. Now it's 6 lines of code. It isn't that easier for new pages-->
<?php
include("../includes/menu.html");
?>
</div>

<div id="content">

<h1><?=$title?>'</h1>

<!--How much of this page is being generated by script? Yes another bit is made up by the db and yes we going into another file--->
<?php
include("../includes/profile.php");
echo '<!--end being in another file. Yes this comment is being echoed out by php.We are now in the .html file.
I set the server up to parse php in html files.
Guess the o.s of the server yet?-->'
?>

<!--This time we are echoing out a function. We have learnt how to use functions in php.-Are we getting clever?-->
<?=getprofile($profile_id)?>

<?php

$internal = array ('http://christine.ycyrffgroupie.co.uk/profiles/profile.html',
		'http://www.ycyrffgroupie.co.uk/profiles/profile.html',
		'http://dev.ycyrffgroupie.co.uk/profiles/profile.html');
if (in_array($_SERVER[HTTP_REFERER],$internal)){
?>
<p><img src="../images/site/back.jpg" width="156" height="44" alt="Back/Yn ol" onClick="history.back()"></p>
<?php
}else{
?>
<p>
<a href="/profiles/profile.html"><img src="../images/site/back.jpg" width="156" height="44" alt="Back/Yn ol"></a>
</p>
<?php
}
?>

</div>

<div style="clear: both;">
</div>
<?php include("../includes/footer.php");?>

</body>

</html>